/**
 * Lista canónica de cargos/puestos de trabajo para usar en selects/dropdowns.
 * Usar esta lista en lugar de extraer cargos de la BD para garantizar
 * opciones consistentes independientemente de los datos existentes.
 */
export const JOB_POSITION_OPTIONS: { value: string; label: string }[] = [
  {
    value: "Administrative Assistant – Forms Team Tabak Law",
    label: "Administrative Assistant – Forms Team Tabak Law",
  },
  { value: "Administrative Director - Andes", label: "Administrative Director - Andes" },
  {
    value: "Administrative Support - Schomburg Insurance",
    label: "Administrative Support - Schomburg Insurance",
  },
  { value: "Agile Coach Tech Lead - Andes", label: "Agile Coach Tech Lead - Andes" },
  { value: "Andes Workforce Liaison", label: "Andes Workforce Liaison" },
  { value: "Assistant Case Manager - WHG", label: "Assistant Case Manager - WHG" },
  { value: "Bankruptcy Assistant - WHG", label: "Bankruptcy Assistant - WHG" },
  { value: "BK Legal Assistant", label: "BK Legal Assistant" },
  { value: "Case Manager - WHG", label: "Case Manager - WHG" },
  { value: "Case Opener - VA (Tabak Law)", label: "Case Opener - VA (Tabak Law)" },
  { value: "Collections & Billing WHG", label: "Collections & Billing WHG" },
  { value: "Collections and Billing Specialist", label: "Collections and Billing Specialist" },
  { value: "Data Entry - WHG", label: "Data Entry - WHG" },
  { value: "Database Administrator - WHG", label: "Database Administrator - WHG" },
  { value: "Document Analyst - CaseScribe", label: "Document Analyst - CaseScribe" },
  {
    value: "English Contract (Statement of Work + Professional Services + Confidentiality)",
    label: "English Contract (Statement of Work + Professional Services + Confidentiality)",
  },
  { value: "ICC Assistant - WHG", label: "ICC Assistant - WHG" },
  { value: "ICC Manager", label: "ICC Manager" },
  { value: "ICC Team Lead - WHG", label: "ICC Team Lead - WHG" },
  { value: "Initial Reconsideration", label: "Initial Reconsideration" },
  {
    value: "Initial Reconsideration - Tabak Law Firm",
    label: "Initial Reconsideration - Tabak Law Firm",
  },
  { value: "Intake Specialist (After Hours) - BK", label: "Intake Specialist (After Hours) - BK" },
  { value: "Intake Specialist - Hill & Ponton", label: "Intake Specialist - Hill & Ponton" },
  { value: "Intake Specialist - Tabak Law", label: "Intake Specialist - Tabak Law" },
  { value: "Intake Specialist - WHG", label: "Intake Specialist - WHG" },
  { value: "Intake Supervisor - Tabak Law", label: "Intake Supervisor - Tabak Law" },
  { value: "Intake Supervisor - WHG", label: "Intake Supervisor - WHG" },
  { value: "Intake Trainer", label: "Intake Trainer" },
  { value: "IT Assistant - Andes", label: "IT Assistant - Andes" },
  { value: "IT Assistant - WHG", label: "IT Assistant - WHG" },
  {
    value: "Jelks Veteran Services - Intake Assistant & Post Intake Records",
    label: "Jelks Veteran Services - Intake Assistant & Post Intake Records",
  },
  { value: "Junior Attorney", label: "Junior Attorney" },
  { value: "Legal Assistant", label: "Legal Assistant" },
  { value: "Legal Assistant - Port Law", label: "Legal Assistant - Port Law" },
  {
    value: "Legal Assistant - Port Law (Part Time)",
    label: "Legal Assistant - Port Law (Part Time)",
  },
  {
    value: "Legal Assistant - SSA Hearing Level (Tabak)",
    label: "Legal Assistant - SSA Hearing Level (Tabak)",
  },
  {
    value: "Legal Assistant - VA Facenotes (Tabak)",
    label: "Legal Assistant - VA Facenotes (Tabak)",
  },
  {
    value: "Legal Assistant - VA File Review (Tabak)",
    label: "Legal Assistant - VA File Review (Tabak)",
  },
  { value: "Legal Assistant - VE", label: "Legal Assistant - VE" },
  { value: "Legal Assistant - Veteran Esquire", label: "Legal Assistant - Veteran Esquire" },
  { value: "Legal Assistant - WHG", label: "Legal Assistant - WHG" },
  { value: "Legal Assistant-Finance (WHG)", label: "Legal Assistant-Finance (WHG)" },
  { value: "Legal Assistant-SSA (Tabak)", label: "Legal Assistant-SSA (Tabak)" },
  {
    value: "Legal Assistant-VA Welcome Calls (Tabak)",
    label: "Legal Assistant-VA Welcome Calls (Tabak)",
  },
  { value: "Legal Case Opener - (VA Tabak Law)", label: "Legal Case Opener - (VA Tabak Law)" },
  { value: "Legal Financial Assistant - WHG", label: "Legal Financial Assistant - WHG" },
  { value: "Mail Sorting - WHG", label: "Mail Sorting - WHG" },
  { value: "Mid-Level Developers", label: "Mid-Level Developers" },
  { value: "Mid-Level Developers Andes Workforce", label: "Mid-Level Developers Andes Workforce" },
  {
    value: "Port Law Hiring – Bankruptcy Assistant",
    label: "Port Law Hiring – Bankruptcy Assistant",
  },
  {
    value: "Professional Services Agreement – Colombia",
    label: "Professional Services Agreement – Colombia",
  },
  { value: "Recruiting Head - Andes", label: "Recruiting Head - Andes" },
  {
    value: "Recruiting Operations Assistant (Remote) – Join Andes Workforce!",
    label: "Recruiting Operations Assistant (Remote) – Join Andes Workforce!",
  },
  { value: "Salesforce Assistant - WHG", label: "Salesforce Assistant - WHG" },
  { value: "Salesforce Developer", label: "Salesforce Developer" },
  { value: "SSA Administrative Assistant", label: "SSA Administrative Assistant" },
  { value: "SSA Hearing Level", label: "SSA Hearing Level" },
  { value: "SSA Initial Reconsideration", label: "SSA Initial Reconsideration" },
  { value: "Switchboard Operator - Tabak Law", label: "Switchboard Operator - Tabak Law" },
  { value: "Testing Invoices", label: "Testing Invoices" },
  { value: "VA Facenotes Specialist", label: "VA Facenotes Specialist" },
  { value: "VA File Review", label: "VA File Review" },
  { value: "VA Intake Specialist", label: "VA Intake Specialist" },
  { value: "VA Team Lead - Tabak Law", label: "VA Team Lead - Tabak Law" },
  { value: "VA Welcome Calls", label: "VA Welcome Calls" },
  {
    value: "WHG - Legal Assistant – Personal Injury Department",
    label: "WHG - Legal Assistant – Personal Injury Department",
  },
  { value: "WHG -Intake Specialist", label: "WHG -Intake Specialist" },
];
